### ISSUE TITLE
Entry for wine is outgreyed - no error text

### ISSUE THREAD

**Issue by ShalokShalom** [solus-project/solus-sc#233]
The installation button is greyed out. There is no info text available, why:

![Bildschirmfoto zu 2019-10-14 22-10-15](https://user-images.githubusercontent.com/6344099/66779813-75974680-eecf-11e9-92a4-3369c4f10c72.png)

**Comment by ShalokShalom** [comment]
This is what it spits out in the command line - where do you do reports on broken packages?

All up to date: 

```
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✓] Rebuilding font cache                                              success
 [✓] Updating desktop database                                          success
 [✓] Updating manpages database                                         success
Systemfehler. Programmausführung abgebrochen.
(-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0061 PANIC: Invalid argument')
Bitte geben Sie 'eopkg help' für die allgemeine Hilfe ein
Verwenden Sie --debug, um einen traceback zu sehen.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/pisi/__init__.py", line 64, in _cleanup
    filesdb.close()
  File "/usr/lib/python2.7/site-packages/pisi/db/filesdb.py", line 94, in close
    self.filesdb.close()
  File "/usr/lib/python2.7/shelve.py", line 146, in close
    self.sync()
  File "/usr/lib/python2.7/shelve.py", line 173, in sync
    self.dict.sync()
  File "/usr/lib/python2.7/bsddb/__init__.py", line 347, in sync
    return _DeadlockWrap(self.db.sync)
  File "/usr/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
DBRunRecoveryError: (-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')
Error in sys.exitfunc:
No handlers could be found for logger "pisi"
Systemfehler. Programmausführung abgebrochen.
(-30973, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')

```

And when I rerun the command to gain an output in English, it says it is already installed. 

It runs the installation script of irfanview and I can use it.

**Comment by JoshStrobl** [comment]
Well, it was installing packages so naturally without a bucket / queue system there isn't a way to install it while existing packages are installing. Guessing you canceled it, which caused eopkg to panic, and your issue with the database can be sorted by https://getsol.us/articles/troubleshooting/general-troubleshooting/en/#eopkg-won-t-install-updates

**Comment by ShalokShalom** [comment]
So there is no bucket / queue system?

And this is the issue?
